#+TITLE: A current perspective on using R and Bioconductor for proteomics data analysis
#+OPTIONS: toc:nil
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="../css/style0.css" />

Laurent Gatto[1][2], Lisa M Breckels[1][2], Thomas Lin Pedersen[4], Vladislav A Petyuk[5], Kathryn S Lilley[2] and Sebastian Gibb[1][3]

[1] [[http://cpu.sysbiol.cam.ac.uk][Computational Proteomics Unit]], Department of Biochemistry, University of Cambridge, Cambridge, UK
[2] [[http://proteomics.bio.cam.ac.uk][Cambridge Centre for Proteomics]], Department of Biochemistry, University of Cambridge, Cambridge, UK
[3] Department of Anesthesiology and Intensive Care, Medical Faculty Carl Gustav Carus, Technical University Dresden, Fetscherstr. 74, 01307 Dresden
[4] Chr. Hansen A/S, Hørsholm, Denmark / Technical University of Denmark, Kgs. Lyngby, Denmark
[5] Biological Sciences Division, Pacific Northwest National Laboratory, Richland, WA, USA

* Introduction and objectives

With the continuous increase in data throughput and experimental
designs complexity, the processing, analysis and interpretation of
proteomics data becomes a major bottleneck that can be tackled by the
appropriate use of statistical and computational tools. The R language
and in particular the Bioconductor project have a major impact on
other fields in high-throughput biology and benefited, in the recent
years, from substantial contributions from the computational
proteomics developers.

* Methods

We summarise some of the latest R and Bioconductor developments in the
field of proteomics, including the support of open community-driven
formats for raw data and identification results, packages for
peptide-spectrum matching, methods quantitative proteomics, mass
spectrometry and quantitation data processing, visualisation and
interpretation.

* Results and Discussion

We provide figures of the number of new package submissions and
downloads over the last Bioconductor releases to illustrate the recent
interest of the proteomics community in the Bioconductor
project. While the command line interface (CLI) represents a
considerable novelty for many life scientists, numerous documentation
and tutorials are available and an increasing number of tools also
provide graphical user interfaces in addition to the CLI. We also
discuss current needs and anticipated developments in the light of
recent progress.

* Conclusions

The R/Bioconductor environment addresses some important issues in
computational proteomics and offers a unique set of interdisciplinary
expertise, capabilities and flexibility in the existing proteomics
software ecosystem. Noteworthy is also the introduction of tools and
technique of R development and usage that permit open and reproducible
computational research and data analysis, an area of increasing
importance in the current data intensive area.


* Resources

- *R* [[http://www.r-project.org/]]
- *Bioconductor* [[http://bioconductor.org/]]
- *RforProteomics* [[http://is.gd/R4Proteomics]]
- *Google group* [[https://is.gd/rbioc_sig_proteomics]]
- *Support site* [[https://support.bioconductor.org]]
- *Poster* 
